# Generated by Django 5.2.8 on 2025-12-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='users/')),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('store', 'Store')], default='user', max_length=10)),
            ],
        ),
    ]
