# Generated by Django 5.2.8 on 2025-12-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=500)),
                ('unit', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True)),
                ('stock_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
