# Generated by Django 5.2.8 on 2025-12-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goapp', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
